In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
print("hello fucking world")

hello fucking world


In [4]:
class hello:
    def __init__ (self,name):
        self.name=name
        print("Initialized !")
    def hello(self):
        print("Hello "+self.name+"!")
    def goodbye(self):
        print("Good Bye "+self.name+"!")
m=hello("You")
m.hello()
m.goodbye()

Initialized !
Hello You!
Good Bye You!


In [12]:
class conv:
    def __init__(self, )
    class onevarequation:
        def __init__(self,a,b,c):
            self.a=a
            self.b=b
            self.c=c
            print("Possible")
        def on(self):
            print(self.a)


a=1
b=1
c=1
m=onevarequation(a,b,c)
m.on()

Possible
1


In [62]:
def conv(equ):
    var=np.array(equ.replace('X+','').replace('Y=','').split())
    print(var)
m='1X+2Y=10'
a = '11223FROM33344INTO33222FROM3344'
a.replace('FROM', ',,,').replace('INTO', ',,,').split(',,,')
conv(m)

['1210']


In [26]:
a = '11223FROM33344INTO33222FROM3344'
a.replace('FROM', ',,,').replace('INTO', ',,,').split(',,,')
a

'11223FROM33344INTO33222FROM3344'

In [30]:
a=[1,2,3,4,5]
b=a
b

[1, 2, 3, 4, 5]

In [31]:
help(np.array)

Help on built-in function array in module numpy.core.multiarray:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K'

In [32]:
a

[1, 2, 3, 4, 5]

In [33]:
b = np.array(a)

In [34]:
b

array([1, 2, 3, 4, 5])

In [36]:
a1 = np.arange(6, 11)

In [37]:
b

array([1, 2, 3, 4, 5])

In [39]:
b=np.append(b,a1)

In [40]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
b.shape(5,5,2)

TypeError: 'tuple' object is not callable

In [44]:
b.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [47]:
a2=np.arange(11,16)

In [48]:
a2

array([11, 12, 13, 14, 15])

In [53]:
b=np.append(b,a2) 
b.np.

ValueError: cannot reshape array of size 30 into shape (3,5)

In [67]:
a = '1x+5y=20'
c=a.replace('x+', ',,,').replace('y=', ',,,').split(',,,')
print(c)


['1', '5', '20']


In [154]:
def conv(equ1,equ2):
#  logic 
#  user input format equ1 :'ax+by=c' and equ2 : 'dx+ey=f'
#  
    var_equ = []  #var equ declaration
    var_sol = []  #var sol declaration
    
    var1 = equ1.replace('x+', ' ').replace('y=', ' ').split(' ')

    for i in np.arange(2):
        var_equ.append(var1[i])
    var_sol.append(var1[2])
    
    if (equ2 is not None):
        var2 =equ2.replace('x+', ' ').replace('y=', ' ').split(' ')
        for i in np.arange(2):
            var_equ.append(var2[i])
        var_sol.append(var2[2])
    
    var_equ = np.array(var_equ)
    var_sol = np.array(var_sol)
    if (equ2 is not None): 
        var_equ = var_equ.reshape(2,2)
        var_sol = var_sol.reshape(2,1)
    
    print(var_equ)
    print(var_sol)
    
m1 = '2x+3y=10'
m2 = '5x+7y=20'
conv(m1,m2)


[['2' '3']
 ['5' '7']]
[['10']
 ['20']]


In [139]:
var_equ.reshape(2,2)

array([[ 3,  5],
       [ 7, 20]])

In [84]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [97]:
z = []
z= np.array(z)

In [108]:
z=[]
a=1
z.append('1','2','3')
z

TypeError: append() takes exactly one argument (3 given)

In [106]:
type(z)

list

In [112]:
z = []
z.append([1,2,3,4])

In [113]:
z

[[1, 2, 3, 4]]

In [114]:
z = np.array(z)

In [115]:
type(z)

numpy.ndarray

In [117]:
z.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [132]:
var_equ=[]
var_equ.append([3,5,7,20])
var_equ = np.array(var_equ)
var_equ.reshape(2,2)

array([[ 3,  5],
       [ 7, 20]])